project:
  output-dir: .

format:
  xbook-cn-pdf:
    pdf-engine: xelatex
    keep-tex: true
    mainfont: "TeX Gyre Pagella"
    CJKmainfont: "Kaiti SC"
    CJKsansfont: "Noto Sans SC"
    CJKmonofont: "Noto Sans SC"
